language: rust
dist: trusty
sudo: false
cache:
  directories:
    - "$HOME/.cargo"
    - "$HOME/rust"
script:
  # https://docs.travis-ci.com/user/pull-requests
  # https://docs.travis-ci.com/user/encryption-keys
  # https://docs.travis-ci.com/user/environment-variables
  - "echo \"TRAVIS: $TRAVIS\""
  - "echo \"TRAVIS_EVENT_TYPE: $TRAVIS_EVENT_TYPE\""
  - "echo \"TRAVIS_JOB_NUMBER: $TRAVIS_JOB_NUMBER\""
  - "echo \"TRAVIS_BRANCH: $TRAVIS_BRANCH\""
  - "echo \"TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST\""
  - "echo \"TRAVIS_PULL_REQUEST_BRANCH: $TRAVIS_PULL_REQUEST_BRANCH\""
  - "echo \"TRAVIS_RUST_VERSION: $TRAVIS_RUST_VERSION\""
  - "echo \"TRAVIS_SECURE_ENV_VARS: $TRAVIS_SECURE_ENV_VARS\""
  # Defined in the env secure section. Can only be decrypted by the Travis secret key
  # attached to rust-lang-ja/temp-travisci-test.
  - "echo \"MY_SECRET_VALUE: $MY_SECRET_VALUE\""
env:
  global:
    secure: "UYZ73AcDKbcKd+inYMR7xGpR4V3cuu+JvC/PzEzdexTXd4575wrGmb2efSbzwwAwV0fixw329F3lfYL03zs5SQMhysCiwpRtV9p6bgJKWEqhCdsq27FOOPyXGdK0cqR206Af7Hlg36fihd2k//Xo4qmWxf4iI29m2+cTX25/utSNXLeeb3WR0Hal3lPsyecjPlPeF+bXoMx68tfGT28zNvwfyXu+evBHQBJy7SNTSpjlk1OIZyoWOQ6p5/67NV61vU/aa4kPram0EjExjJJjo0Fspc8gbvszXc6vZiLrt8elzHAXB7PJpsXNHA2z3rEy+koEbdeLKOeupnMVn17woS58lS+sqKhSryzSgHB5y+ZNLmPmFB1J9X751cXhMJcmfJ84wvG5c6D56P85JZxpVLFK5D+LgsHNYKr125WW4Zy6Hf0TATrfz4ph7M5Y5NfcuBz+6WNVUJbt9bbDpV6Z4foMbEMRzMDDA1aO1AjiHDpmLI+mZt1dVmtPOkBsHNpMI5ZTlb4bYdW1jzTOXJxHXIw6PeBIAZPgWmB/3Vm7Kkt7r/rC0Cud3rO72Swo6rcgkHTe5zMk/IeOPHEukmKZhOO5y8eIDuM4ck/6cHudYcULUEVSB3j85rwGDUAt5e6yKWZTGDqn3fJWHJHvkhfHE6x0ZW2Ccn7ltHVfzAsrjtc="
